dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/data/download/
        - $HOME/miniconda3/
        - $HOME/download/

before_install:
  - bash .travis/travis_before_install.sh
  - export PATH="/home/travis/miniconda3/bin:$PATH"
install:
  - bash src/install/conda_env.sh
  - bash src/install/from_tarball.sh
  - source activate smsk_gatk_germline
  - Rscript src/install/from_cran.R
  - source deactivate smsk_gatk_germline

script:
  - source activate smsk_gatk_germline
  - snakemake -j
