samples:
    papa:
        lib1:
            forward: data/reads/papa.read1.fq.gz
            reverse: data/reads/papa.read2.fq.gz
            molecule: dna
            type: PE
            phred: phred33
            adaptor: None
    paalt:
        lib1:
            forward: data/reads/paalt.read1.fq.gz
            reverse: data/reads/paalt.read2.fq.gz
            molecule: dna
            type: PE
            phred: phred33
            adaptor: None
    altalt:
        lib1:
            forward: data/reads/altalt.read1.fq.gz
            reverse: data/reads/altalt.read2.fq.gz
            molecule: dna
            type: PE
            phred: phred33
            adaptor: None

reference:
    data/reference/chr19_chr19_KI270866v1_alt.fasta

alternative:
    data/reference/chr19_chr19_KI270866v1_alt.fasta.alt
